### ISSUE TITLE
Adding a new bookings

### ISSUE THREAD

**Issue by Jeberlen** [karlpet/bookings#2]
### What?
When adding a new booking there is an editable text field that I guess is the subject of a meeting? 
But the issue with this is: 
When a meeting is booked and the widget is closed, reentry into the widget for that booking will display the Employee who was selected on additions name, instead of the subject.
Changing this field again will however work. 

In steps:
 - Open the react application
 - Add a booking
 - Click outside of the modal to close it
 - Click the same booking.
 - Here you can see the faulty value of the editable text field
 - Replace the employee name with something else
 - close the modal and reenter
 - The "correct" value should still be present.

---
### Where?
The highest entry point for this issue should reside in `bookinginterface/src/components/bookingmodal.js` at line `52:9`

**Comment by carlsve** [comment]
its supposed to go by name. The input is old code from the example.
